# Generated by Django 5.2.1 on 2025-06-01 14:38

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AllowedOrigin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origin', models.URLField(unique=True)),
                ('note', models.CharField(blank=True, max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='ContactPageSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Contact Us', max_length=100)),
                ('slug', models.SlugField(default='contact', max_length=100, unique=True)),
                ('hero_title', models.CharField(default='Get in Touch', max_length=200)),
                ('hero_subtitle', models.TextField(blank=True, default="We'd love to hear from you. Send us a message and we'll respond as soon as possible.")),
                ('form_title', models.CharField(default='Send us a Message', max_length=200)),
                ('address_section_title', models.CharField(default='Visit Us', max_length=100)),
                ('address_line1', models.CharField(blank=True, max_length=100)),
                ('address_line2', models.CharField(blank=True, max_length=100)),
                ('address_line3', models.CharField(blank=True, max_length=100)),
                ('address_line4', models.CharField(blank=True, max_length=100)),
                ('phone_section_title', models.CharField(default='Call Us', max_length=100)),
                ('phone_number', models.CharField(blank=True, max_length=50)),
                ('business_hours', models.TextField(blank=True, help_text='Enter business hours, one per line')),
                ('email_section_title', models.CharField(default='Email Us', max_length=100)),
                ('general_email', models.EmailField(blank=True, max_length=254)),
                ('support_email', models.EmailField(blank=True, max_length=254)),
                ('sales_email', models.EmailField(blank=True, max_length=254)),
                ('social_section_title', models.CharField(default='Follow Us', max_length=100)),
                ('facebook_url', models.URLField(blank=True)),
                ('instagram_url', models.URLField(blank=True)),
                ('twitter_url', models.URLField(blank=True)),
            ],
            options={
                'verbose_name': 'Contact Page Settings',
                'verbose_name_plural': 'Contact Page Settings',
            },
        ),
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('subject', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Contact Message',
                'verbose_name_plural': 'Contact Messages',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['is_read'], name='core_contac_is_read_c89f0a_idx'), models.Index(fields=['created_at'], name='core_contac_created_63cb1b_idx')],
            },
        ),
    ]
