# Generated by Django 5.2.1 on 2025-06-02 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='Corrison Store', max_length=100)),
                ('site_tagline', models.CharField(blank=True, help_text='Short description/tagline for your site', max_length=200)),
                ('site_domain', models.CharField(default='example.com', max_length=100)),
                ('site_logo', models.ImageField(blank=True, null=True, upload_to='site/logos/')),
                ('site_logo_url', models.URLField(blank=True, help_text='Alternative to uploading logo file')),
                ('favicon', models.ImageField(blank=True, null=True, upload_to='site/favicons/')),
                ('contact_email', models.EmailField(default='contact@example.com', max_length=254)),
                ('support_email', models.EmailField(blank=True, max_length=254)),
                ('sales_email', models.EmailField(blank=True, max_length=254)),
                ('support_phone', models.CharField(default='+1 123-456-7890', max_length=20)),
                ('address_line1', models.CharField(blank=True, max_length=100)),
                ('address_line2', models.CharField(blank=True, max_length=100)),
                ('city', models.CharField(blank=True, max_length=50)),
                ('state', models.CharField(blank=True, max_length=50)),
                ('postal_code', models.CharField(blank=True, max_length=20)),
                ('country', models.CharField(blank=True, max_length=50)),
                ('facebook_url', models.URLField(blank=True)),
                ('instagram_url', models.URLField(blank=True)),
                ('twitter_url', models.URLField(blank=True)),
                ('youtube_url', models.URLField(blank=True)),
                ('linkedin_url', models.URLField(blank=True)),
                ('tiktok_url', models.URLField(blank=True)),
                ('primary_color', models.CharField(default='#0d6efd', help_text='Hex color code (e.g., #0d6efd)', max_length=7)),
                ('secondary_color', models.CharField(default='#6c757d', help_text='Hex color code (e.g., #6c757d)', max_length=7)),
                ('accent_color', models.CharField(default='#fd7e14', help_text='Hex color code (e.g., #fd7e14)', max_length=7)),
                ('font_primary', models.CharField(default="'Inter', sans-serif", max_length=100)),
                ('font_headings', models.CharField(default="'Poppins', sans-serif", max_length=100)),
                ('google_analytics_id', models.CharField(blank=True, help_text='Google Analytics tracking ID', max_length=50)),
                ('facebook_pixel_id', models.CharField(blank=True, help_text='Facebook Pixel ID', max_length=50)),
                ('google_tag_manager_id', models.CharField(blank=True, help_text='Google Tag Manager ID', max_length=50)),
                ('enable_wishlist', models.BooleanField(default=True)),
                ('enable_reviews', models.BooleanField(default=True)),
                ('enable_newsletter', models.BooleanField(default=True)),
                ('enable_blog', models.BooleanField(default=True)),
                ('enable_cart', models.BooleanField(default=True)),
                ('currency_symbol', models.CharField(default='$', max_length=5)),
                ('currency_code', models.CharField(default='USD', max_length=3)),
                ('tax_rate', models.DecimalField(decimal_places=4, default=0.1, help_text='Tax rate as decimal (e.g., 0.10 for 10%)', max_digits=5)),
                ('enabled_payment_methods', models.JSONField(blank=True, default=list, help_text='JSON array of enabled payment methods, e.g., ["stripe", "paypal"]')),
                ('shipping_methods', models.JSONField(blank=True, default=dict, help_text='JSON object with shipping method configurations')),
                ('products_per_page', models.PositiveIntegerField(default=12)),
                ('related_products_limit', models.PositiveIntegerField(default=4)),
                ('featured_products_limit', models.PositiveIntegerField(default=8)),
                ('business_hours', models.TextField(blank=True, help_text='Enter business hours, one per line')),
                ('footer_copyright_text', models.CharField(blank=True, max_length=200)),
                ('footer_description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Site Settings',
                'verbose_name_plural': 'Site Settings',
            },
        ),
    ]
