# Generated by Django 5.2 on 2025-05-23 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_allowedorigin'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactPageSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address_line1', models.CharField(blank=True, max_length=100)),
                ('address_line2', models.CharField(blank=True, max_length=100)),
                ('address_line3', models.CharField(blank=True, max_length=100)),
                ('address_line4', models.CharField(blank=True, max_length=100)),
                ('phone_number', models.CharField(blank=True, max_length=50)),
                ('business_hours', models.TextField(blank=True, help_text='Enter business hours, one per line')),
                ('general_email', models.EmailField(blank=True, max_length=254)),
                ('support_email', models.EmailField(blank=True, max_length=254)),
                ('sales_email', models.EmailField(blank=True, max_length=254)),
                ('facebook_url', models.URLField(blank=True)),
                ('instagram_url', models.URLField(blank=True)),
                ('twitter_url', models.URLField(blank=True)),
                ('hero_title', models.CharField(default='Get in Touch', max_length=200)),
                ('hero_subtitle', models.TextField(blank=True, default="We'd love to hear from you. Send us a message and we'll respond as soon as possible.")),
                ('form_title', models.CharField(default='Send us a Message', max_length=200)),
                ('address_section_title', models.CharField(default='Visit Us', max_length=100)),
                ('phone_section_title', models.CharField(default='Call Us', max_length=100)),
                ('email_section_title', models.CharField(default='Email Us', max_length=100)),
                ('social_section_title', models.CharField(default='Follow Us', max_length=100)),
            ],
            options={
                'verbose_name': 'Contact Page Settings',
                'verbose_name_plural': 'Contact Page Settings',
            },
        ),
    ]
