# Generated by Django 5.2 on 2025-05-23 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_contactpagesettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactpagesettings',
            name='slug',
            field=models.SlugField(default='contact', max_length=100, unique=True),
        ),
        migrations.AddField(
            model_name='contactpagesettings',
            name='title',
            field=models.CharField(default='Contact Us', max_length=100),
        ),
    ]
