# Generated by Django 5.2.1 on 2025-06-01 14:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('title', models.CharField(max_length=200)),
                ('subtitle', models.CharField(blank=True, max_length=400)),
                ('content', models.TextField(help_text='Rich text / HTML')),
                ('meta_description', models.CharField(blank=True, max_length=300)),
                ('is_published', models.BooleanField(default=False)),
                ('published_at', models.DateTimeField(blank=True, help_text='Date/time when this page goes live', null=True)),
                ('order', models.PositiveIntegerField(default=0, help_text='Lower numbers appear first')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('hero_title', models.CharField(blank=True, max_length=200)),
                ('hero_subtitle', models.CharField(blank=True, max_length=300)),
                ('hero_content', models.TextField(blank=True, help_text='Rich text for hero section')),
                ('hero_image', models.ImageField(blank=True, null=True, upload_to='pages/hero/')),
                ('hero_image_url', models.URLField(blank=True, help_text='Public URL of the hero image (leave blank if uploading a file instead).')),
                ('hero_right_content', models.TextField(blank=True, help_text='Optional text content for right side of hero (displays INSTEAD of an image if provided)')),
                ('hero_button_text', models.CharField(blank=True, help_text='Text for hero CTA button', max_length=100)),
                ('hero_button_url', models.URLField(blank=True, help_text='URL for hero CTA button')),
                ('middle_section_title', models.CharField(blank=True, help_text='Title for middle text section', max_length=200)),
                ('middle_section_content', models.TextField(blank=True, help_text='Rich text / HTML for middle section')),
                ('end_section_title', models.CharField(blank=True, help_text='Title for end text section', max_length=200)),
                ('end_section_content', models.TextField(blank=True, help_text='Rich text / HTML for end section')),
                ('has_feature_section', models.BooleanField(default=False)),
                ('feature_section_title', models.CharField(blank=True, max_length=200)),
            ],
            options={
                'ordering': ['order', '-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='PageFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100)),
                ('content', models.TextField()),
                ('icon', models.CharField(blank=True, help_text='Icon name or class', max_length=100)),
                ('order', models.PositiveIntegerField(default=0)),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='features', to='pages.page')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
