# Generated by Django 5.2.1 on 2025-06-03 06:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('title', models.CharField(blank=True, help_text='Job title or role', max_length=100)),
                ('company', models.CharField(blank=True, max_length=100)),
                ('content', models.TextField(help_text='Testimonial content')),
                ('image', models.ImageField(blank=True, help_text='Photo of the person giving testimonial', null=True, upload_to='testimonials/')),
                ('rating', models.PositiveIntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], default=5, help_text='Star rating (1-5)')),
                ('category', models.CharField(blank=True, help_text="Category for filtering (e.g., 'product', 'service', 'general')", max_length=50)),
                ('is_featured', models.BooleanField(default=False, help_text='Mark as featured testimonial')),
                ('order', models.PositiveIntegerField(default=0, help_text='Display order (lower numbers first)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['order', '-created_at'],
            },
        ),
        migrations.AddField(
            model_name='page',
            name='countdown_target_date',
            field=models.DateTimeField(blank=True, help_text='Target date/time for countdown timer', null=True),
        ),
        migrations.AddField(
            model_name='page',
            name='countdown_title',
            field=models.CharField(blank=True, help_text='Title above countdown timer', max_length=100),
        ),
        migrations.AddField(
            model_name='page',
            name='hero_button_2_text',
            field=models.CharField(blank=True, help_text='Text for secondary CTA button', max_length=100),
        ),
        migrations.AddField(
            model_name='page',
            name='hero_button_2_url',
            field=models.URLField(blank=True, help_text='URL for secondary CTA button'),
        ),
        migrations.AddField(
            model_name='page',
            name='hero_video_url',
            field=models.URLField(blank=True, help_text='External video URL (YouTube, Vimeo, etc.) for hero background'),
        ),
        migrations.AddField(
            model_name='page',
            name='page_type',
            field=models.CharField(choices=[('page', 'Regular Page'), ('landing', 'Landing Page')], default='page', help_text='Type of page - affects available features', max_length=20),
        ),
        migrations.AddField(
            model_name='page',
            name='prelaunch_badge_text',
            field=models.CharField(blank=True, default='Coming Soon', help_text='Text for prelaunch badge', max_length=50),
        ),
        migrations.AddField(
            model_name='page',
            name='show_countdown',
            field=models.BooleanField(default=False, help_text='Display countdown timer in hero section'),
        ),
        migrations.AddField(
            model_name='page',
            name='show_prelaunch_badge',
            field=models.BooleanField(default=False, help_text="Show 'Coming Soon' or custom badge in hero"),
        ),
        migrations.AddField(
            model_name='page',
            name='show_scroll_indicator',
            field=models.BooleanField(default=True, help_text='Show scroll down indicator in hero section'),
        ),
        migrations.AddField(
            model_name='page',
            name='show_social_proof',
            field=models.BooleanField(default=False, help_text='Display social proof section with testimonials'),
        ),
        migrations.AddField(
            model_name='page',
            name='social_proof_title',
            field=models.CharField(blank=True, help_text='Title for social proof section', max_length=100),
        ),
        migrations.CreateModel(
            name='PageTestimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0, help_text='Display order on this page')),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='page_testimonials', to='pages.page')),
                ('testimonial', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pages.testimonial')),
            ],
            options={
                'ordering': ['order'],
                'unique_together': {('page', 'testimonial')},
            },
        ),
    ]
