# Generated by Django 5.2 on 2025-05-08 07:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_page_published_at_alter_page_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='feature_section_title',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='page',
            name='has_feature_section',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='page',
            name='hero_content',
            field=models.TextField(blank=True, help_text='Rich text for hero section'),
        ),
        migrations.AddField(
            model_name='page',
            name='hero_subtitle',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='page',
            name='hero_title',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.CreateModel(
            name='PageFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100)),
                ('content', models.TextField()),
                ('icon', models.CharField(blank=True, help_text='Icon name or class', max_length=100)),
                ('order', models.PositiveIntegerField(default=0)),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='features', to='pages.page')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
