# Generated by Django 5.2 on 2025-05-18 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_page_feature_section_title_page_has_feature_section_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='end_section_content',
            field=models.TextField(blank=True, help_text='Rich text / HTML for end section'),
        ),
        migrations.AddField(
            model_name='page',
            name='end_section_title',
            field=models.CharField(blank=True, help_text='Title for end text section', max_length=200),
        ),
        migrations.AddField(
            model_name='page',
            name='hero_button_text',
            field=models.CharField(blank=True, help_text='Text for hero CTA button', max_length=100),
        ),
        migrations.AddField(
            model_name='page',
            name='hero_button_url',
            field=models.URLField(blank=True, help_text='URL for hero CTA button'),
        ),
        migrations.AddField(
            model_name='page',
            name='middle_section_content',
            field=models.TextField(blank=True, help_text='Rich text / HTML for middle section'),
        ),
        migrations.AddField(
            model_name='page',
            name='middle_section_title',
            field=models.CharField(blank=True, help_text='Title for middle text section', max_length=200),
        ),
    ]
