# Generated by Django 5.2 on 2025-05-20 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_page_end_section_content_page_end_section_title_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='hero_image_url',
            field=models.URLField(blank=True, help_text='Public URL of the hero image (leave blank if uploading a file instead).'),
        ),
    ]
