# Generated by Django 5.2 on 2025-05-21 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_page_hero_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='hero_right_content',
            field=models.TextField(blank=True, help_text='Optional text content for right side of hero (displays INSTEAD of an image if provided)'),
        ),
    ]
