# Generated by Django 5.2.1 on 2025-06-07 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_profile_email_verification_sent_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='password_reset_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='password_reset_token',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
