# Generated by Django 5.2 on 2025-05-04 11:21

import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('content', tinymce.models.HTMLField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('featured_image', models.ImageField(blank=True, help_text='Optional main image for the post', null=True, upload_to='blog/images/')),
                ('youtube_url', models.URLField(blank=True, help_text='Optional YouTube embed URL')),
                ('attachment', models.FileField(blank=True, help_text='Optional PDF or other file to download', null=True, upload_to='blog/attachments/')),
                ('is_featured', models.BooleanField(default=False)),
            ],
        ),
    ]
