# Generated by Django 5.2 on 2025-05-07 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blogpost',
            options={'ordering': ['-published_at', '-created_at']},
        ),
        migrations.AddField(
            model_name='blogpost',
            name='is_published',
            field=models.BooleanField(default=False, help_text='Publish this post when checked'),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='published_at',
            field=models.DateTimeField(blank=True, help_text='Date/time when this post goes live', null=True),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='attachment',
            field=models.FileField(blank=True, help_text='Optional file to download', null=True, upload_to='blog/attachments/'),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='is_featured',
            field=models.BooleanField(default=False, help_text='Flag featured posts'),
        ),
    ]
