# Generated by Django 5.2 on 2025-05-21 18:13

import django.db.models.deletion
import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_alter_blogpost_content'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Blog Category',
                'verbose_name_plural': 'Blog Categories',
                'ordering': ['name'],
            },
        ),
        migrations.AlterModelOptions(
            name='blogpost',
            options={'ordering': ['-published_at', '-created_at'], 'verbose_name': 'Blog Post', 'verbose_name_plural': 'Blog Posts'},
        ),
        migrations.RemoveField(
            model_name='blogpost',
            name='is_published',
        ),
        migrations.AddField(
            model_name='blogpost',
            name='ad_code',
            field=tinymce.models.HTMLField(blank=True, help_text='HTML/JavaScript ad code (for AdSense)'),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='ad_image',
            field=models.ImageField(blank=True, help_text='Banner image for advertisement', null=True, upload_to='blog/ads/'),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='ad_type',
            field=models.CharField(choices=[('none', 'No Advertisement'), ('adsense', 'Google AdSense'), ('banner', 'Banner Image')], default='none', max_length=10),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='ad_url',
            field=models.URLField(blank=True, help_text='URL for ad banner to link to'),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='external_image_url',
            field=models.URLField(blank=True, help_text='External URL for post image (use instead of uploading)', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='meta_description',
            field=models.CharField(blank=True, help_text='SEO Description (160 characters max)', max_length=160),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='meta_keywords',
            field=models.CharField(blank=True, help_text='Comma-separated keywords', max_length=255),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='meta_title',
            field=models.CharField(blank=True, help_text='SEO Title (60 characters max)', max_length=60),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('archived', 'Archived')], default='draft', max_length=10),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='thumbnail',
            field=models.ImageField(blank=True, help_text='Small image for listings (falls back to main image if not provided)', null=True, upload_to='blog/thumbnails/'),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='attachment',
            field=models.FileField(blank=True, help_text='Optional file for users to download', null=True, upload_to='blog/attachments/'),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='featured_image',
            field=models.ImageField(blank=True, help_text='Main image for the post', null=True, upload_to='blog/images/'),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='is_featured',
            field=models.BooleanField(default=False, help_text='Feature this post on the homepage'),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='youtube_url',
            field=models.URLField(blank=True, help_text='YouTube embed URL'),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='posts', to='blog.blogcategory'),
        ),
    ]
