# Generated by Django 5.2 on 2025-05-21 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_blogcategory_alter_blogpost_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='ad_code',
            field=models.TextField(blank=True, help_text='HTML/JavaScript ad code (for AdSense)'),
        ),
    ]
