# Generated by Django 5.2.1 on 2025-06-10 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0002_order_appointment_customer_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_title', models.CharField(default='Order History', help_text='Main heading for the order history page', max_length=200)),
                ('page_subtitle', models.CharField(blank=True, help_text='Optional subtitle below the main heading', max_length=300)),
                ('page_description', models.TextField(default='Track your orders, view details, and manage your purchases.', help_text='Description text below the heading')),
            ],
            options={
                'verbose_name': 'Order Page Settings',
                'verbose_name_plural': 'Order Page Settings',
            },
        ),
    ]
