# Generated by Django 5.2.1 on 2025-06-06 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='external_course_url',
            field=models.URLField(blank=True, help_text='Link to paid course on Udemy, Teachable, etc.', null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='external_platform',
            field=models.CharField(blank=True, help_text="e.g., 'Udemy', 'Teachable', 'Skillshare'", max_length=50),
        ),
    ]
