# Generated by Django 5.2.1 on 2025-06-06 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_course_external_course_url_course_external_platform'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('page_title', models.CharField(default='Learn New Skills', help_text='Main heading for the courses page', max_length=200)),
                ('page_subtitle', models.CharField(blank=True, help_text='Optional subtitle below the main heading', max_length=300)),
                ('page_description', models.TextField(default='Discover our comprehensive collection of courses designed to help you learn and grow. From beginner to advanced levels, find the perfect course for your journey.', help_text='Description text below the heading')),
                ('external_course_1_title', models.CharField(blank=True, help_text='Title for first external course link', max_length=100)),
                ('external_course_1_url', models.URLField(blank=True, help_text='URL for first external course')),
                ('external_course_2_title', models.CharField(blank=True, help_text='Title for second external course link', max_length=100)),
                ('external_course_2_url', models.URLField(blank=True, help_text='URL for second external course')),
                ('external_course_3_title', models.CharField(blank=True, help_text='Title for third external course link', max_length=100)),
                ('external_course_3_url', models.URLField(blank=True, help_text='URL for third external course')),
            ],
            options={
                'verbose_name': 'Course Page Settings',
                'verbose_name_plural': 'Course Page Settings',
            },
        ),
    ]
