# Generated by Django 5.2.1 on 2025-06-01 14:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LinkHub',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('background_image', models.ImageField(blank=True, help_text='Optional background image for the link page', null=True, upload_to='linkhub/backgrounds/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.PositiveIntegerField(default=0, help_text='Lower numbers appear first')),
                ('is_published', models.BooleanField(default=False, help_text='Publish this hub when checked')),
                ('published_at', models.DateTimeField(blank=True, help_text='Date/time when this hub goes live', null=True)),
            ],
            options={
                'ordering': ['order', '-published_at', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('url', models.URLField()),
                ('media_type', models.CharField(choices=[('link', 'Standard Link'), ('video', 'Video'), ('pdf', 'PDF Document'), ('audio', 'Audio/Podcast'), ('image', 'Image'), ('donation', 'Donation/Tip')], default='link', help_text='Type of media this link represents', max_length=10)),
                ('icon', models.CharField(blank=True, help_text="Icon name or class (e.g., 'heart', 'star', 'music')", max_length=100)),
                ('description', models.TextField(blank=True, help_text='Short description of this link or media item')),
                ('author', models.CharField(blank=True, help_text='Creator or author of this content (optional)', max_length=100)),
                ('order', models.PositiveIntegerField(default=0)),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links', to='linkhub.linkhub')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
