# Generated by Django 5.2 on 2025-05-07 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('linkhub', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='linkhub',
            options={'ordering': ['-published_at', '-created_at']},
        ),
        migrations.AddField(
            model_name='linkhub',
            name='is_published',
            field=models.BooleanField(default=False, help_text='Publish this hub when checked'),
        ),
        migrations.AddField(
            model_name='linkhub',
            name='published_at',
            field=models.DateTimeField(blank=True, help_text='Date/time when this hub goes live', null=True),
        ),
    ]
