# Generated by Django 5.2 on 2025-05-08 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('linkhub', '0002_alter_linkhub_options_linkhub_is_published_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='linkhub',
            options={'ordering': ['order', '-published_at', '-created_at']},
        ),
        migrations.AddField(
            model_name='link',
            name='author',
            field=models.CharField(blank=True, help_text='Creator or author of this content (optional)', max_length=100),
        ),
        migrations.AddField(
            model_name='link',
            name='description',
            field=models.TextField(blank=True, help_text='Short description of this link or media item'),
        ),
        migrations.AddField(
            model_name='link',
            name='media_type',
            field=models.CharField(choices=[('link', 'Standard Link'), ('video', 'Video'), ('pdf', 'PDF Document'), ('audio', 'Audio/Podcast'), ('image', 'Image')], default='link', help_text='Type of media this link represents', max_length=10),
        ),
        migrations.AddField(
            model_name='linkhub',
            name='order',
            field=models.PositiveIntegerField(default=0, help_text='Lower numbers appear first'),
        ),
        migrations.AlterField(
            model_name='link',
            name='icon_url',
            field=models.URLField(blank=True, help_text='Optional icon, thumbnail or preview image'),
        ),
    ]
