# Generated by Django 5.2 on 2025-05-22 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('linkhub', '0004_rename_icon_to_icon_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='linkhub',
            name='background_image',
            field=models.ImageField(blank=True, help_text='Optional background image for the link page', null=True, upload_to='linkhub/backgrounds/'),
        ),
        migrations.AlterField(
            model_name='link',
            name='media_type',
            field=models.CharField(choices=[('link', 'Standard Link'), ('video', 'Video'), ('pdf', 'PDF Document'), ('audio', 'Audio/Podcast'), ('image', 'Image'), ('donation', 'Donation/Tip')], default='link', help_text='Type of media this link represents', max_length=10),
        ),
    ]
