# Generated by Django 5.2 on 2025-05-22 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('linkhub', '0005_linkhub_background_image_alter_link_media_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='link',
            name='icon_url',
        ),
        migrations.AddField(
            model_name='link',
            name='icon',
            field=models.CharField(blank=True, help_text="Icon name or class (e.g., 'heart', 'star', 'music')", max_length=100),
        ),
    ]
