# Generated by Django 5.2.1 on 2025-06-06 06:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='availability',
            options={'ordering': ['date', 'start_time'], 'verbose_name': 'Availability Override', 'verbose_name_plural': 'Availability Overrides'},
        ),
        migrations.RemoveField(
            model_name='calendaruser',
            name='default_availability',
        ),
        migrations.AddField(
            model_name='calendaruser',
            name='friday_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='calendaruser',
            name='friday_end',
            field=models.TimeField(default=datetime.time(17, 0)),
        ),
        migrations.AddField(
            model_name='calendaruser',
            name='friday_start',
            field=models.TimeField(default=datetime.time(9, 0)),
        ),
        migrations.AddField(
            model_name='calendaruser',
            name='monday_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='calendaruser',
            name='monday_end',
            field=models.TimeField(default=datetime.time(17, 0)),
        ),
        migrations.AddField(
            model_name='calendaruser',
            name='monday_start',
            field=models.TimeField(default=datetime.time(9, 0)),
        ),
        migrations.AddField(
            model_name='calendaruser',
            name='saturday_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='calendaruser',
            name='saturday_end',
            field=models.TimeField(default=datetime.time(15, 0)),
        ),
        migrations.AddField(
            model_name='calendaruser',
            name='saturday_start',
            field=models.TimeField(default=datetime.time(10, 0)),
        ),
        migrations.AddField(
            model_name='calendaruser',
            name='sunday_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='calendaruser',
            name='sunday_end',
            field=models.TimeField(default=datetime.time(16, 0)),
        ),
        migrations.AddField(
            model_name='calendaruser',
            name='sunday_start',
            field=models.TimeField(default=datetime.time(12, 0)),
        ),
        migrations.AddField(
            model_name='calendaruser',
            name='thursday_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='calendaruser',
            name='thursday_end',
            field=models.TimeField(default=datetime.time(17, 0)),
        ),
        migrations.AddField(
            model_name='calendaruser',
            name='thursday_start',
            field=models.TimeField(default=datetime.time(9, 0)),
        ),
        migrations.AddField(
            model_name='calendaruser',
            name='tuesday_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='calendaruser',
            name='tuesday_end',
            field=models.TimeField(default=datetime.time(17, 0)),
        ),
        migrations.AddField(
            model_name='calendaruser',
            name='tuesday_start',
            field=models.TimeField(default=datetime.time(9, 0)),
        ),
        migrations.AddField(
            model_name='calendaruser',
            name='wednesday_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='calendaruser',
            name='wednesday_end',
            field=models.TimeField(default=datetime.time(17, 0)),
        ),
        migrations.AddField(
            model_name='calendaruser',
            name='wednesday_start',
            field=models.TimeField(default=datetime.time(9, 0)),
        ),
        migrations.AlterField(
            model_name='availability',
            name='is_available',
            field=models.BooleanField(default=True, help_text='False = blocked time, True = available time (overrides default schedule)'),
        ),
        migrations.AlterField(
            model_name='calendaruser',
            name='is_calendar_active',
            field=models.BooleanField(default=True, help_text='Whether this calendar is accepting bookings'),
        ),
    ]
