# Generated by Django 5.2.1 on 2025-06-06 08:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0002_alter_availability_options_and_more'),
        ('checkout', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='order',
            field=models.OneToOneField(blank=True, help_text='Associated order if this is a paid appointment', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appointment', to='checkout.order'),
        ),
    ]
