# Generated by Django 5.2.1 on 2025-06-10 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0003_appointment_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppointmentSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_title', models.CharField(default='Your Appointments', help_text='Main heading for the appointments page', max_length=200)),
                ('page_subtitle', models.CharField(blank=True, help_text='Optional subtitle below the main heading', max_length=300)),
                ('page_description', models.TextField(default='View and manage all your appointments in one place.', help_text='Description text below the heading')),
            ],
            options={
                'verbose_name': 'Appointment Page Settings',
                'verbose_name_plural': 'Appointment Page Settings',
            },
        ),
        migrations.CreateModel(
            name='CalendarSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_title', models.CharField(default='Book An Appointment', help_text='Main heading for the calendar booking page', max_length=200)),
                ('page_subtitle', models.CharField(blank=True, help_text='Optional subtitle below the main heading', max_length=300)),
                ('page_description', models.TextField(default='Select your preferred date and time from our available slots.', help_text='Description text below the heading')),
                ('booking_instructions', models.TextField(blank=True, help_text='Additional instructions shown on the booking page')),
            ],
            options={
                'verbose_name': 'Calendar Page Settings',
                'verbose_name_plural': 'Calendar Page Settings',
            },
        ),
    ]
