# Generated by Django 5.2 on 2025-05-24 06:32

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='token',
            field=models.CharField(blank=True, db_index=True, max_length=500, null=True),
        ),
        migrations.AddIndex(
            model_name='cart',
            index=models.Index(fields=['token'], name='cart_cart_token_285649_idx'),
        ),
    ]
