# Generated by Django 5.2.1 on 2025-06-18 13:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
        ('products', '0002_alter_product_in_stock'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cart',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveIndex(
            model_name='cart',
            name='cart_cart_user_id_b645f9_idx',
        ),
        migrations.RemoveIndex(
            model_name='cart',
            name='cart_cart_session_5e1af5_idx',
        ),
        migrations.RemoveIndex(
            model_name='cart',
            name='cart_cart_token_285649_idx',
        ),
        migrations.RemoveIndex(
            model_name='cart',
            name='cart_cart_is_acti_96bd76_idx',
        ),
        migrations.RemoveIndex(
            model_name='cartitem',
            name='cart_cartit_cart_id_4fb076_idx',
        ),
        migrations.RemoveIndex(
            model_name='cartitem',
            name='cart_cartit_product_985dba_idx',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='has_digital_items',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='has_physical_items',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='token',
        ),
        migrations.AlterField(
            model_name='cart',
            name='session_key',
            field=models.CharField(blank=True, db_index=True, max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='cart',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='carts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='cart',
            index=models.Index(fields=['session_key', 'is_active'], name='cart_cart_session_3c25be_idx'),
        ),
        migrations.AddIndex(
            model_name='cart',
            index=models.Index(fields=['user', 'is_active'], name='cart_cart_user_id_5d777a_idx'),
        ),
        migrations.AddIndex(
            model_name='cartitem',
            index=models.Index(fields=['cart', 'product'], name='cart_cartit_cart_id_4bd8c3_idx'),
        ),
    ]
