# Generated by Django 5.2.1 on 2025-05-27 10:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_alter_product_id'),
    ]

    operations = [
        # Drop the existing foreign key constraint
        migrations.RunSQL(
            sql="ALTER TABLE products_productimage DROP CONSTRAINT IF EXISTS products_productimage_product_id_fkey CASCADE;",
            reverse_sql="-- Cannot reverse this operation"
        ),
        
        # Convert the product_id column from bigint to uuid
        migrations.RunSQL(
            sql="ALTER TABLE products_productimage ALTER COLUMN product_id TYPE uuid USING product_id::text::uuid;",
            reverse_sql="-- Cannot reverse this operation"
        ),
        
        # Re-create the foreign key constraint
        migrations.RunSQL(
            sql="""
            ALTER TABLE products_productimage 
            ADD CONSTRAINT products_productimage_product_id_fkey 
            FOREIGN KEY (product_id) REFERENCES products_product(id) 
            DEFERRABLE INITIALLY DEFERRED;
            """,
            reverse_sql="-- Cannot reverse this operation"
        ),
    ]