# Generated by Django 5.2.1 on 2025-05-27 11:08
from django.db import migrations

class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_fix_productimage_uuid_foreign_key'),
    ]

    operations = [
        # Drop the existing foreign key constraint for ProductVariant
        migrations.RunSQL(
            sql="ALTER TABLE products_productvariant DROP CONSTRAINT IF EXISTS products_productvariant_product_id_fkey CASCADE;",
            reverse_sql="-- Cannot reverse this operation"
        ),
        
        # Convert the product_id column from bigint to uuid
        migrations.RunSQL(
            sql="ALTER TABLE products_productvariant ALTER COLUMN product_id TYPE uuid USING product_id::text::uuid;",
            reverse_sql="-- Cannot reverse this operation"
        ),
        
        # Re-create the foreign key constraint
        migrations.RunSQL(
            sql="""
            ALTER TABLE products_productvariant 
            ADD CONSTRAINT products_productvariant_product_id_fkey 
            FOREIGN KEY (product_id) REFERENCES products_product(id) 
            DEFERRABLE INITIALLY DEFERRED;
            """,
            reverse_sql="-- Cannot reverse this operation"
        ),
    ]